# Generated by Django 3.2.5 on 2021-07-22 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autobid',
            name='user',
            field=models.ManyToManyField(related_name='users', to='users.UserDetails'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userdetails'),
        ),
        migrations.AlterField(
            model_name='item',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='users.userdetails'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userdetails'),
        ),
    ]
